# This is a basic workflow to help you get started with Actions

name: SynthEdit Plugin CI

env:
  PROJECT_NAME: 'PD303'
  SYNTHEDIT_EXE: 'C:\Program Files\SynthEdit 1.5\SynthEdit.exe'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download and Cache File
        uses: valadaptive/download-file-action@v0.1.0
        with:
          url: http://synthedit.com/beta/Install_SynthEdit_64bit.exe
          max-age: 86400
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./Install_SynthEdit_64bit.exe /quiet

      # Runs a set of commands using the runners shell
      # todo /rego $(SynthEditRegoKey) /regoname "$(SynthEditRegoName)"
      - name: Run a multi-line script
        run: |
          "$SYNTHEDIT_EXE" "${{github.workspace}}$PROJECT_NAME\SE_Project\$PROJECT_NAME.synthedit" /autosavejuce /quiet"

          dir ${{github.workspace}}
